# Generated by Django 4.2.4 on 2023-08-29 21:26

import datetime
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('unit', models.CharField(choices=[('Cups', 'Cups'), ('TBSP', 'TBSP'), ('TSP', 'TSP'), ('Oz', 'Oz'), ('Lbs', 'Lbs'), ('gal', 'gal'), ('ea', 'ea'), ('g', 'g'), ('mg', 'mg'), ('kg', 'kg')], default='ea', max_length=50)),
                ('quantity', models.IntegerField(validators=[django.core.validators.MaxValueValidator(254)])),
                ('in_stock', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Steps',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('step_number', models.IntegerField(validators=[django.core.validators.MaxValueValidator(254)])),
                ('step_text', models.TextField()),
                ('is_complete', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('serves', models.IntegerField(validators=[django.core.validators.MaxValueValidator(200)])),
                ('tags', models.JSONField(blank=True, default=None)),
                ('created_at', models.DateField(default=datetime.datetime(2023, 8, 29, 14, 26, 51, 3601))),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
