# Generated by Django 4.2.4 on 2023-08-29 21:28

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='created_at',
            field=models.DateField(default=datetime.datetime(2023, 8, 29, 14, 28, 53, 728151)),
        ),
    ]
